import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/sidebar.html')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
})

test('uses canonical active state and expands every active ancestor', async ({ page }) => {
  const sidebar = page.locator('[data-bw-sidebar][data-name="workspace"]')
  await expect(sidebar.locator('[data-item-name="orders"]')).toHaveAttribute('data-active', 'true')
  await expect(sidebar.locator('[data-item-name="orders"] > *')).toHaveAttribute('aria-current', 'page')
  await expect(sidebar.locator('[data-item-name="overview"]')).toHaveAttribute('data-active', 'false')
  await expect(sidebar.locator('[data-group-name="workspace"]')).toHaveAttribute('data-expanded', 'true')
  await expect(sidebar.locator('[data-group-name="workspace"] > .bw-sidebar-group-panel')).toBeVisible()
  expect(await page.evaluate(() => document.activeElement === document.body)).toBe(true)
})

test('desktop collapse and group helpers preserve independent nested state', async ({ page }) => {
  const workspace = page.locator('[data-bw-sidebar][data-name="workspace"]')
  const secondary = page.locator('[data-bw-sidebar][data-name="secondary"]')
  expect(await page.evaluate(() => expandSidebarGroup('workspace', 'customers'))).toBe(true)
  expect(await page.evaluate(() => expandSidebarGroup('workspace', 'segments'))).toBe(true)
  expect(await page.evaluate(() => collapseSidebar('workspace'))).toBe(true)
  await expect(workspace).toHaveAttribute('data-state', 'collapsed')
  await expect(workspace.locator('[data-group-name="customers"]')).toHaveAttribute('data-expanded', 'true')
  await expect(secondary).toHaveAttribute('data-state', 'expanded')
  expect(await page.evaluate(() => expandSidebar('workspace'))).toBe(true)
  expect(await page.evaluate(() => collapseSidebarGroup('workspace', 'customers'))).toBe(true)
  expect(await page.evaluate(() => toggleSidebarGroup('workspace', 'customers'))).toBe(true)
  expect(await page.evaluate(() => toggleSidebarGroup('missing', 'customers'))).toBe(false)
})

test('cancelable state events stop group and desktop changes', async ({ page }) => {
  const workspace = page.locator('[data-bw-sidebar][data-name="workspace"]')
  await page.evaluate(() => { window.blockGroup = true })
  expect(await page.evaluate(() => collapseSidebarGroup('workspace', 'workspace'))).toBe(false)
  await expect(workspace.locator('[data-group-name="workspace"]')).toHaveAttribute('data-expanded', 'true')
  await page.evaluate(() => {
    document.querySelector('[data-bw-sidebar][data-name="workspace"]').addEventListener('bladewind:sidebar:before-collapse', (event) => event.preventDefault(), {once: true})
  })
  expect(await page.evaluate(() => collapseSidebar('workspace'))).toBe(false)
  await expect(workspace).toHaveAttribute('data-state', 'expanded')
})

test('valid persistence restores state and invalid persistence is ignored', async ({ page }) => {
  expect(await page.evaluate(() => collapseSidebar('workspace'))).toBe(true)
  expect(await page.evaluate(() => expandSidebarGroup('workspace', 'reports'))).toBe(true)
  await page.reload()
  const workspace = page.locator('[data-bw-sidebar][data-name="workspace"]')
  await expect(workspace).toHaveAttribute('data-state', 'collapsed')
  await expect(workspace.locator('[data-group-name="reports"]')).toHaveAttribute('data-expanded', 'true')

  await page.evaluate(() => localStorage.setItem('sidebar-e2e', JSON.stringify({collapsed: 'bad', groups: []})))
  await page.reload()
  await expect(workspace).toHaveAttribute('data-state', 'expanded')
  await expect(workspace.locator('[data-group-name="reports"]')).toHaveAttribute('data-expanded', 'false')
  expect(await page.evaluate(() => resetSidebar('workspace'))).toBe(true)
  expect(await page.evaluate(() => localStorage.getItem('sidebar-e2e'))).toBeNull()
})

test('keyboard navigation skips disabled items and supports nested LTR and RTL behavior', async ({ page }) => {
  const workspace = page.locator('[data-bw-sidebar][data-name="workspace"]')
  const group = workspace.locator('[data-group-name="workspace"] > [data-bw-sidebar-group-trigger]')
  await group.focus()
  await page.keyboard.press('ArrowDown')
  await expect(workspace.locator('[data-item-name="overview"] > *')).toBeFocused()
  await page.keyboard.press('End')
  await expect(workspace.locator('[data-group-name="reports"] > [data-bw-sidebar-group-trigger]')).toBeFocused()
  await page.keyboard.press('Home')
  await expect(group).toBeFocused()
  await page.keyboard.press('Space')
  await expect(workspace.locator('[data-group-name="workspace"]')).toHaveAttribute('data-expanded', 'false')
  await page.keyboard.press('Enter')
  await expect(workspace.locator('[data-group-name="workspace"]')).toHaveAttribute('data-expanded', 'true')

  const customers = workspace.locator('[data-group-name="customers"] > [data-bw-sidebar-group-trigger]')
  await customers.focus()
  await page.keyboard.press('ArrowRight')
  await expect(workspace.locator('[data-group-name="customers"]')).toHaveAttribute('data-expanded', 'true')

  const rtl = page.locator('[data-bw-sidebar][data-name="rtl-sidebar"]')
  const rtlGroup = rtl.locator('[data-group-name="account"] > [data-bw-sidebar-group-trigger]')
  await rtlGroup.focus()
  await page.keyboard.press('ArrowLeft')
  await expect(rtl.locator('[data-group-name="account"]')).toHaveAttribute('data-expanded', 'true')
})

test('mobile Drawer opens, traps focus, closes by helper and restores focus', async ({ page }) => {
  await page.setViewportSize({width: 390, height: 844})
  const trigger = page.locator('#open-workspace')
  const drawer = page.locator('[data-bw-drawer][data-name="workspace-mobile"]')
  await trigger.click()
  await expect(drawer).toBeVisible()
  await expect(drawer.locator('[data-bw-sidebar][data-name="workspace"]')).toHaveCount(1)
  await expect(page.locator('nav[aria-label="Workspace navigation"]')).toHaveCount(1)
  await expect(page.locator('body')).toHaveClass(/overflow-hidden/)
  await expect(drawer.locator('[data-bw-sidebar-close]')).toBeFocused()
  expect(await page.evaluate(() => closeSidebar('workspace'))).toBe(true)
  await expect(drawer).toBeHidden()
  await expect(trigger).toBeFocused()
  await expect(page.locator('body')).not.toHaveClass(/overflow-hidden/)
})

test('mobile Escape, backdrop, cancelable close and item auto-close use Drawer behavior', async ({ page }) => {
  await page.setViewportSize({width: 390, height: 844})
  const drawer = page.locator('[data-bw-drawer][data-name="workspace-mobile"]')
  await page.locator('#open-workspace').click()
  await page.evaluate(() => { window.blockClose = true })
  await page.keyboard.press('Escape')
  await expect(drawer).toBeVisible()
  await page.evaluate(() => { window.blockClose = false })
  await page.keyboard.press('Escape')
  await expect(drawer).toBeHidden()

  await page.locator('#open-workspace').click()
  await drawer.locator('[data-bw-drawer-backdrop]').click({position: {x: 385, y: 5}})
  await expect(drawer).toBeHidden()

  await page.locator('#open-workspace').click()
  await drawer.locator('[data-item-name="refresh"] button').click()
  await expect(drawer).toBeHidden()
  const events = await page.evaluate(() => window.sidebarEvents)
  expect(events.some((event) => event.type === 'bladewind:sidebar:item-activate' && event.itemName === 'refresh')).toBe(true)
})

test('right and logical RTL placement resolve to the correct mobile edge', async ({ page }) => {
  await page.setViewportSize({width: 390, height: 844})
  await page.locator('#open-secondary').click()
  let panel = page.locator('[data-bw-drawer][data-name="secondary-mobile"] .bw-drawer-panel')
  await expect(panel).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 0)')
  let box = await panel.boundingBox()
  expect(box.x + box.width).toBeCloseTo(390, 0)
  await page.keyboard.press('Escape')

  await page.locator('#open-rtl').click()
  panel = page.locator('[data-bw-drawer][data-name="rtl-sidebar-mobile"] .bw-drawer-panel')
  await expect(panel).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, 0)')
  box = await panel.boundingBox()
  expect(box.x + box.width).toBeCloseTo(390, 0)
})

test('large trees scroll internally with sticky regions, dark mode, reduced motion and no page overflow', async ({ page }) => {
  await page.emulateMedia({reducedMotion: 'reduce'})
  expect(await page.evaluate(() => expandSidebarGroup('workspace', 'reports'))).toBe(true)
  const sidebar = page.locator('[data-bw-sidebar][data-name="workspace"]')
  const navigation = sidebar.locator('.bw-sidebar-navigation')
  const scroll = await navigation.evaluate((element) => ({scrollHeight: element.scrollHeight, clientHeight: element.clientHeight, overflowY: getComputedStyle(element).overflowY}))
  expect(scroll.scrollHeight).toBeGreaterThan(scroll.clientHeight)
  expect(scroll.overflowY).toBe('auto')
  await expect(sidebar.locator('.bw-sidebar-header')).toHaveCSS('position', 'sticky')
  await expect(sidebar.locator('.bw-sidebar-footer')).toHaveCSS('position', 'sticky')
  await expect(sidebar).toHaveCSS('transition-duration', '1e-05s')
  await expect(page.locator('#secondary-shell [data-bw-sidebar]')).toHaveCSS('background-color', 'rgb(28, 31, 36)')
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)
  expect(overflow).toBeLessThanOrEqual(1)
})
